### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by lucaszischka** [LucasMucGH/BottomSheet#11]
This is a collection of features that are on my To-Do list. Each feature is briefly explained and a possible solution is described.

Any feedback for further features or comments on the features (whether they are redundant or ideas for implementation) are welcomed. No ETA is and will be provided.

# Decided
- Add support for iPad, Mac and horizontally rotated iPhones (see #3)
  - _If you have a look at how Apple Maps displays the BottomSheet on the iPad or the iPhone when it is horizontally rotated, you will get the idea. I want to add this "floating" implementation._
- Add an option to make the BottomSheet height dynamic to its content size (see #17)

# Declined
- Add threshold for `swipeToDismiss` (see #8).
  - _The current implementation doesn't need a threshold, because it is dynamic. It uses the flick through feature to decide when it should get dismissed._
- Make BottomSheet not go above 100% (see #8)
  - _If the BottomSheet gets dragged above the full screen height(100%), it snaps back to the highest value in the BottomSheetPosition enum. And because no value should be above 1, it will never be unreachable._
- Transition to `OptionSet` for `BottomSheet.Options`
  - _`OptionSet` does not work with associated values, so it can't replace my current attempt._

# Other 
- The default values of `BottomSheetPosition` still do not match Apple's. I've tried countless ways, but unfortunately couldn't find out how apple calculates the height in the different states.
- The `sheetBackground` modifier still needs the View to be erased to AnyView. I have no idea how to make it better as an enum cannot have a `some View` or a `generic type`.

**Comment by TariqAlmazyad** [comment]
Beautiful work .

**Comment by NathHorrigan** [comment]
Hey @LucasMucGH  - Any idea on when we might see functionality for `appleScrollBehavior`?

**Comment by LucasMucGH** [comment]
Hey @NathHorrigan,
as long as i don’t find a way to prevent a ScrollView from scrolling i can’t tell you a estimated arrival time.
Greetings Lucas

**Comment by blandinf** [comment]
It will be possible with the new update to update topCornerRadius and background blur color? 
Thanks for your work!

**Comment by LucasMucGH** [comment]
> It will be possible with the new update to update topCornerRadius and background blur color?

Yes, I put it on my list. Greetings Lucas

**Comment by dewit** [comment]
@LucasMucGH Hi Lucas, love this package, thanks for creating it. Could you share a timeframe for some of the decided features in this list? It would greatly enhance the app I'm working on. Thanks in advance. Keep up the good work :)

**Comment by LucasMucGH** [comment]
Hello Arjan,

im currently very busy and don’t have much time going into expanding the project.
I wont share a ETA because this is a project I do for fun in my free time and I don’t want to stress myself, by setting deadlines.
As soon as I have more time again I will continue expanding this project and I will add more features, but for the time being, the best option if you want to see new features is to make a pull request and adding them yourself. Sorry about that.

Greetings,
Lucas

**Comment by dewit** [comment]
> Hello Arjan,
> 
> im currently very busy and don’t have much time going into expanding the project. I wont share a ETA because this is a project I do for fun in my free time and I don’t want to stress myself, by setting deadlines. As soon as I have more time again I will continue expanding this project and I will add more features, but for the time being, the best option if you want to see new features is to make a pull request and adding them yourself. Sorry about that.
> 
> Greetings, Lucas

I get that completely! No problem at all. Thanks anyway :)

**Comment by Sherlouk** [comment]
Hey @LucasMucGH 👋  Just wanted to say what a lovely library this is. I've been exploring a few alternatives (mostly including Apple's own new one) and this has so many awesome features in comparison to theirs 👏 

Was going to raise a ticket but realised somebody raised it before me, so would love to +1 on number 15 (pull down the sheet instead of scrolling the ScrollView when at the top). I understand you're not spending too much time on this at the moment 🙂  I may look to open a PR (time permitting on my side too aha!).

Awesome work regardless ❤️

**Comment by flowbe** [comment]
I'd love to see the dynamic height feature! Hope it's implemented soon 🙏🏻
Awesome work nonetheless!
