### ISSUE TITLE
Allow background customisation

### ISSUE THREAD

**Issue by mschinis** [LucasMucGH/BottomSheet#14]
Hello,

The `backgroundBlur` option in light mode works well when the background is something colorful, but when it's white/nearly white you can't distinguish the sheet from the background.

Adding a screenshot to help explain the above.

<img width="378" alt="Screenshot 2021-06-10 at 17 17 54" src="https://user-images.githubusercontent.com/771903/121544103-5e409180-ca01-11eb-94e1-36e976917ef3.png">

Can we add a new option to allow customising the background color?

**Comment by mschinis** [comment]
ah just noticed you have the same feature in the pipeline in #11

**Comment by LucasMucGH** [comment]
Yes this is an feature I’m planning to implement, but right now I didn’t find a pretty way to make it working :(

**Comment by mschinis** [comment]
@LucasMucGH happy to help with the transition if needed, let me know

**Comment by LucasMucGH** [comment]
@mschinis I don't think the transition is possible, because we are using associated values with the enum cases. But if you find a way to make it work it would be really helpful.
It would also be really appreciated to make the `.background(AnyView)` option work without having to wrap it in `AnyView`. If you have any ideas please let me know or file a pull request.

Greetings Lucas
