### ISSUE TITLE
Drag Indicator (Capsule) not clickable

### ISSUE THREAD

**Issue by LucasMucGH** [LucasMucGH/BottomSheet#2]
For some unknown reason you can't tap on the capsule to change the state of the BottomSheet.

If anyone knows what's the problem here please report it. 

Thank you.

**Comment by dbarsamian** [comment]
One solution is to add a `.onTapGesture` modifier to the `Capsule` view, and remove the view from the `Button` label closure. Adding the `switchPositionIndicator` call inside this modifier results in the expected behavior.

For some reason, the `Button` does not recognize the `Capsule` in its label as something that can be tapped - replacing it with a normal `Text` view results in the expected behavior.
