### ISSUE TITLE
Example screenshots/gif in readme not showing

### ISSUE THREAD

**Issue by shreyaspapi** [LucasMucGH/BottomSheet#27]

**Comment by LucasMucGH** [comment]
Yes this is because I’m using [Git Large File Storage](https://git-lfs.github.com/) for the Gifs (because it would be nonsense to include them in project clones) and the free limit of Git LFS is around 1GB upload/download I think and after 1.5GB it is not loading/showing them anymore until the next month; so the real problem is that this project is currently having to much traffic/clones for the free plan 😂.

But I think I will look into other solutions for storing the files, because I don’t think the traffic will slow down, but I also don’t want to pay for helping other developers by sharing my code for free. As soon as I have an working solution I will close this issue, but for now I will leave it open.
