### ISSUE TITLE
Not Readable for one long line.

### ISSUE THREAD

**Issue by recherst** [LucasMucGH/BottomSheet#28]
So would you mind to wrap one line to multiple line for better reading? PR welcome?

**Comment by jordibruin** [comment]
What is this referring to?

**Comment by recherst** [comment]
> What is this referring to?

For example, in file ViewExtension.swift those functions and comments are too long for reading, I think wrap line should be better.

**Comment by LucasMucGH** [comment]
Hello Yonggang,

im not sure if you are referring to the documentation comments or the actual source code or something different.

If you are referring to the documentation comments, they are not intended for being read inside the code, but for XCode to preview more details on how to use it. So it makes no difference here how long the lines are.

If you are referring to the source code, the same goes here; this is my current type of writing code and styling code. If you prefer it in a different way, you can always use my code and change it however you like and even publish it, because it is licensed under the MIT Licence. But I can work better with less lines and therefore sometimes less readable code.

Greetings,
Lucas

**Comment by recherst** [comment]
> Hello Yonggang,
> 
> im not sure if you are referring to the documentation comments or the actual source code or something different.
> 
> If you are referring to the documentation comments, they are not intended for being read inside the code, but for XCode to preview more details on how to use it. So it makes no difference here how long the lines are.
> 
> If you are referring to the source code, the same goes here; this is my current type of writing code and styling code. If you prefer it in a different way, you can always use my code and change it however you like and even publish it, because it is licensed under the MIT Licence. But I can work better with less lines and therefore sometimes less readable code.
> 
> Greetings,
> Lucas

Respect your writing style.

**Comment by lucaszischka** [comment]
Just found this issue and wanted to mention that I changed my writing style in your favour. Im using SwiftLint, which enforces shorter line length.

**Comment by recherst** [comment]
> Just found this issue and wanted to mention that I changed my writing style in your favour. Im using SwiftLint, which enforces shorter line length.

Well done~ hope you like it!
