### ISSUE TITLE
SlideUp Animation inherited by content?

### ISSUE THREAD

**Issue by nneubauer** [LucasMucGH/BottomSheet#30]
Hi! First of all, thanks for making this library open source!

I encountered a strange "bug" of which I am not sure if it is BottomSheet related or maybe something wrong in SwiftUI or SDWebImage.

I have a an SDWebImage in my BottomSheet that does load asynchronously. In fact the image will already be cached, but it is transformed to a smaller size async and then the placeholder box will be replaced by the image. What is odd is, that the when the image appears, it kind of "chases" the animation of bottom sheet sliding up but it is a bit slower than the bottom sheet which looks slightly odd. Here are some screenshots of how the animation looks like:

![bottomSheet](https://user-images.githubusercontent.com/1698019/135265254-247260df-a1e8-4962-8064-8636f3175d78.gif)

I have not any custom animations applied and I suspect that BottomSheet somehow inherits their animations properties to the image but maybe I am completely wrong. Any hints appreciated.

**Comment by LucasMucGH** [comment]
Hello Nicolas,

first of all, thank you for your kind words.

This “bug” is in fact related to this libary. To be exact this behavior is on purpose, because:

When the BottomSheet is opened, it slides up from the bottom. If the content of the BottomSheet, wouldn’t have the same animation it would just appear in the middle of the screen. This would look odd and not be expected by the most users.

In your specific case this causes an odd look, because the following happens (I would guess):
- The BottomSheet appears
- The BottomSheet and content get animated to move up
- The placeholder (as part of the content) gets animated too
- Now the placeholder gets replaced by a new view (the picture), which causes the animation to start over
- Now the animations are not synced

To fix this, I recommend you to play around with the `.animation()` modifier until you get it to look right.
Maybe try adding `.animation(nil)` to the view of the picture and leave the placeholder untouched. Or change the animation delay of the picture to something negativ. 

I don’t even know if there is an perfekt solution for your problem and unfortunately it is not something I can fix.

I will close this issue, because there is nothing I can do about it, but if you need further assistance, don’t hesitate to share some code or ask me questions below.

Grüße aus München,
Lucas

**Comment by nneubauer** [comment]
Hmmm, I see. Thanks for your detailed response. I already played with the .animation() modifier, but couldn't get it to work. Will investigate further.

Grüße aus Düsseldorf,
Nicolas ;)
