### ISSUE TITLE
Use simultaneousGesture to allow inner drag gestures

### ISSUE THREAD

**Issue by ValeriyJefimov** [LucasMucGH/BottomSheet#41]
Hi, Lucas.

What about to add an option to use `.simultaneousGesture(DragGesture()) ` to use other drag gestures in nested content?

Thanx

**Comment by LucasMucGH** [comment]
This is a good idea and could close #35. I will implement it tomorrow. Thank you!

**Comment by ValeriyJefimov** [comment]
😀

**Comment by LucasMucGH** [comment]
Hello Valeriy Jefimov,

unfortunately I had a lot of work until now, which caused the 7 days delay. Anyway, I don't think that I the option is needed, because the native implementation works just fine: 

```swift
Color.black
            .ignoresSafeArea()
            .bottomSheet(bottomSheetPosition: self.$bottomSheetPosition, options: []) {
                    Text("Hello BottomSheet!")
            }
            .simultaneousGesture(
                DragGesture()
                    .onChanged({ value in
                        print(value)
                    })
                    .onEnded({ value in
                        print(value)
                    })
            )
```

Only when using a scroll view it stops working, but this is a general SwiftUI problem (as to my knowledge).

If I misunderstood you, don't hesitate to tell me.

Greetings from Germany,
Lucas
