### ISSUE TITLE
Dragging inner content

### ISSUE THREAD

**Issue by Thongvor** [LucasMucGH/BottomSheet#6]
Hey, is there a way to move the outer view by dragging only the inner scroll?
(like in Apple Maps app, Find My by Apple, Google Maps)

for example UIKit solutions: 
UBottomSheet - https://github.com/OfTheWolf/UBottomSheet
ClassPass app - https://medium.com/classpass-engineering/creating-a-fluid-scroll-experience-on-ios-faeb29be3bdb

**Comment by LucasMucGH** [comment]
Yes currently we don’t support this behavior by default, but you can implement it your own like this:

```
(...), mainContent: {
    if self.bottomSheetPosition == .top {
        ScrollView {
            Text("Hello World!")
        }
    } else {
        Text("Hello World!")
    }
}
(...)
```

**Comment by TariqAlmazyad** [comment]
> Yes currently we don’t support this behavior by default, but you can implement it your own like this:
> 
> ```
> (...), mainContent: {
>     if self.bottomSheetPosition == .top {
>         ScrollView {
>             Text("Hello World!")
>         }
>     } else {
>         Text("Hello World!")
>     }
> }
> (...)
> ```

I believe the issuer wants to have it to behave like this  
By modifying the following code in VStask {}
<img width="637" alt="Screen Shot 2021-05-27 at 1 34 17 PM" src="https://user-images.githubusercontent.com/34104180/119812242-9c618f80-bef0-11eb-872f-f665a1c1470d.png">

The current version can not be dragged when for example you hold on the text , instead of the upper BottomView in the drawer , and drag it . 

the photo code fixes it . 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/34104180/119812684-11cd6000-bef1-11eb-9c75-408d46c8c7bc.gif)

**Comment by LucasMucGH** [comment]
> I believe the issuer wants to have it to behave like this
By modifying the following code in VStask {}

I’m not sure about that. If you have a look at Apple Maps for example you will see that Apple has the content in a ScrollView, but you can’t scroll the ScrollView until you are at the top position.

https://user-images.githubusercontent.com/63545066/119891580-6eed0400-bf39-11eb-9afd-d05916b869ef.mp4

But maybe @Thongvor can bring light in the dark :)

**Comment by LucasMucGH** [comment]
I will now close this issue because all features have been moved to #11.
